// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfpvoisybupscqbjykfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmcHZvaXN5YnVwc2NxYmp5a2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1MjMzMTAsImV4cCI6MjA4NDA5OTMxMH0.q6jHA3V8EI7rlG6YFmFI3I7l-ZQWcgGE2XQOJEsW22o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
